/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RetailerRouteRouteImport } from './routes/retailer/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetailerIndexRouteImport } from './routes/retailer/index'
import { Route as RetailerProfileRouteImport } from './routes/retailer/profile'
import { Route as RetailerOrdersRouteImport } from './routes/retailer/orders'
import { Route as RetailerOrderRouteImport } from './routes/retailer/order'
import { Route as RetailerLedgerRouteImport } from './routes/retailer/ledger'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedShareLogRouteImport } from './routes/_authenticated/share-log'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedRouteOptimizationRouteImport } from './routes/_authenticated/route-optimization'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReconcileRouteImport } from './routes/_authenticated/reconcile'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPaymentRemindersRouteImport } from './routes/_authenticated/payment-reminders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDemandConsolidationRouteImport } from './routes/_authenticated/demand-consolidation'
import { Route as AuthenticatedDeliveryStatusRouteImport } from './routes/_authenticated/delivery-status'
import { Route as AuthenticatedDeliveryDemandRouteImport } from './routes/_authenticated/delivery-demand'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCratesRouteImport } from './routes/_authenticated/crates'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as AuthenticatedCashReconciliationRouteImport } from './routes/_authenticated/cash-reconciliation'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedSuppliersIdRouteImport } from './routes/_authenticated/suppliers.$id'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedPurchasesChallanRouteImport } from './routes/_authenticated/purchases.challan'
import { Route as AuthenticatedOrdersNewRouteImport } from './routes/_authenticated/orders.new'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedCustomerLedgerIdRouteImport } from './routes/_authenticated/customer-ledger.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerRouteRoute = RetailerRouteRouteImport.update({
  id: '/retailer',
  path: '/retailer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerIndexRoute = RetailerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RetailerRouteRoute,
} as any)
const RetailerProfileRoute = RetailerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RetailerRouteRoute,
} as any)
const RetailerOrdersRoute = RetailerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => RetailerRouteRoute,
} as any)
const RetailerOrderRoute = RetailerOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => RetailerRouteRoute,
} as any)
const RetailerLedgerRoute = RetailerLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => RetailerRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShareLogRoute = AuthenticatedShareLogRouteImport.update({
  id: '/share-log',
  path: '/share-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRouteOptimizationRoute =
  AuthenticatedRouteOptimizationRouteImport.update({
    id: '/route-optimization',
    path: '/route-optimization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconcileRoute = AuthenticatedReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentRemindersRoute =
  AuthenticatedPaymentRemindersRouteImport.update({
    id: '/payment-reminders',
    path: '/payment-reminders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandConsolidationRoute =
  AuthenticatedDemandConsolidationRouteImport.update({
    id: '/demand-consolidation',
    path: '/demand-consolidation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryStatusRoute =
  AuthenticatedDeliveryStatusRouteImport.update({
    id: '/delivery-status',
    path: '/delivery-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryDemandRoute =
  AuthenticatedDeliveryDemandRouteImport.update({
    id: '/delivery-demand',
    path: '/delivery-demand',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCratesRoute = AuthenticatedCratesRouteImport.update({
  id: '/crates',
  path: '/crates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashReconciliationRoute =
  AuthenticatedCashReconciliationRouteImport.update({
    id: '/cash-reconciliation',
    path: '/cash-reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersIdRoute =
  AuthenticatedSuppliersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSuppliersRoute,
  } as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/purchases/new',
    path: '/purchases/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesChallanRoute =
  AuthenticatedPurchasesChallanRouteImport.update({
    id: '/purchases/challan',
    path: '/purchases/challan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersNewRoute = AuthenticatedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerLedgerIdRoute =
  AuthenticatedCustomerLedgerIdRouteImport.update({
    id: '/customer-ledger/$id',
    path: '/customer-ledger/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/retailer': typeof RetailerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cash-reconciliation': typeof AuthenticatedCashReconciliationRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/crates': typeof AuthenticatedCratesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/delivery-demand': typeof AuthenticatedDeliveryDemandRoute
  '/delivery-status': typeof AuthenticatedDeliveryStatusRoute
  '/demand-consolidation': typeof AuthenticatedDemandConsolidationRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-reminders': typeof AuthenticatedPaymentRemindersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reconcile': typeof AuthenticatedReconcileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/route-optimization': typeof AuthenticatedRouteOptimizationRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/share-log': typeof AuthenticatedShareLogRoute
  '/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/retailer/ledger': typeof RetailerLedgerRoute
  '/retailer/order': typeof RetailerOrderRoute
  '/retailer/orders': typeof RetailerOrdersRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/': typeof RetailerIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/customer-ledger/$id': typeof AuthenticatedCustomerLedgerIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/purchases/challan': typeof AuthenticatedPurchasesChallanRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cash-reconciliation': typeof AuthenticatedCashReconciliationRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/crates': typeof AuthenticatedCratesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/delivery-demand': typeof AuthenticatedDeliveryDemandRoute
  '/delivery-status': typeof AuthenticatedDeliveryStatusRoute
  '/demand-consolidation': typeof AuthenticatedDemandConsolidationRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-reminders': typeof AuthenticatedPaymentRemindersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reconcile': typeof AuthenticatedReconcileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/route-optimization': typeof AuthenticatedRouteOptimizationRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/share-log': typeof AuthenticatedShareLogRoute
  '/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/retailer/ledger': typeof RetailerLedgerRoute
  '/retailer/order': typeof RetailerOrderRoute
  '/retailer/orders': typeof RetailerOrdersRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer': typeof RetailerIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/customer-ledger/$id': typeof AuthenticatedCustomerLedgerIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/purchases/challan': typeof AuthenticatedPurchasesChallanRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/retailer': typeof RetailerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/cash-reconciliation': typeof AuthenticatedCashReconciliationRoute
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/crates': typeof AuthenticatedCratesRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/delivery-demand': typeof AuthenticatedDeliveryDemandRoute
  '/_authenticated/delivery-status': typeof AuthenticatedDeliveryStatusRoute
  '/_authenticated/demand-consolidation': typeof AuthenticatedDemandConsolidationRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payment-reminders': typeof AuthenticatedPaymentRemindersRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reconcile': typeof AuthenticatedReconcileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/route-optimization': typeof AuthenticatedRouteOptimizationRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/share-log': typeof AuthenticatedShareLogRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/retailer/ledger': typeof RetailerLedgerRoute
  '/retailer/order': typeof RetailerOrderRoute
  '/retailer/orders': typeof RetailerOrdersRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/': typeof RetailerIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/customer-ledger/$id': typeof AuthenticatedCustomerLedgerIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/orders/new': typeof AuthenticatedOrdersNewRoute
  '/_authenticated/purchases/challan': typeof AuthenticatedPurchasesChallanRoute
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/retailer'
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cash-reconciliation'
    | '/claims'
    | '/crates'
    | '/customers'
    | '/dashboard'
    | '/deliveries'
    | '/delivery-demand'
    | '/delivery-status'
    | '/demand-consolidation'
    | '/expenses'
    | '/inventory'
    | '/notifications'
    | '/payment-reminders'
    | '/payments'
    | '/products'
    | '/reconcile'
    | '/reports'
    | '/route-optimization'
    | '/routes'
    | '/settings'
    | '/share-log'
    | '/suppliers'
    | '/retailer/ledger'
    | '/retailer/order'
    | '/retailer/orders'
    | '/retailer/profile'
    | '/retailer/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/customer-ledger/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/orders/new'
    | '/purchases/challan'
    | '/purchases/new'
    | '/suppliers/$id'
    | '/invoices/'
    | '/orders/'
    | '/purchases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cash-reconciliation'
    | '/claims'
    | '/crates'
    | '/customers'
    | '/dashboard'
    | '/deliveries'
    | '/delivery-demand'
    | '/delivery-status'
    | '/demand-consolidation'
    | '/expenses'
    | '/inventory'
    | '/notifications'
    | '/payment-reminders'
    | '/payments'
    | '/products'
    | '/reconcile'
    | '/reports'
    | '/route-optimization'
    | '/routes'
    | '/settings'
    | '/share-log'
    | '/suppliers'
    | '/retailer/ledger'
    | '/retailer/order'
    | '/retailer/orders'
    | '/retailer/profile'
    | '/retailer'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/customer-ledger/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/orders/new'
    | '/purchases/challan'
    | '/purchases/new'
    | '/suppliers/$id'
    | '/invoices'
    | '/orders'
    | '/purchases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/retailer'
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/cash-reconciliation'
    | '/_authenticated/claims'
    | '/_authenticated/crates'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/delivery-demand'
    | '/_authenticated/delivery-status'
    | '/_authenticated/demand-consolidation'
    | '/_authenticated/expenses'
    | '/_authenticated/inventory'
    | '/_authenticated/notifications'
    | '/_authenticated/payment-reminders'
    | '/_authenticated/payments'
    | '/_authenticated/products'
    | '/_authenticated/reconcile'
    | '/_authenticated/reports'
    | '/_authenticated/route-optimization'
    | '/_authenticated/routes'
    | '/_authenticated/settings'
    | '/_authenticated/share-log'
    | '/_authenticated/suppliers'
    | '/retailer/ledger'
    | '/retailer/order'
    | '/retailer/orders'
    | '/retailer/profile'
    | '/retailer/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/customer-ledger/$id'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/orders/new'
    | '/_authenticated/purchases/challan'
    | '/_authenticated/purchases/new'
    | '/_authenticated/suppliers/$id'
    | '/_authenticated/invoices/'
    | '/_authenticated/orders/'
    | '/_authenticated/purchases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RetailerRouteRoute: typeof RetailerRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer': {
      id: '/retailer'
      path: '/retailer'
      fullPath: '/retailer'
      preLoaderRoute: typeof RetailerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer/': {
      id: '/retailer/'
      path: '/'
      fullPath: '/retailer/'
      preLoaderRoute: typeof RetailerIndexRouteImport
      parentRoute: typeof RetailerRouteRoute
    }
    '/retailer/profile': {
      id: '/retailer/profile'
      path: '/profile'
      fullPath: '/retailer/profile'
      preLoaderRoute: typeof RetailerProfileRouteImport
      parentRoute: typeof RetailerRouteRoute
    }
    '/retailer/orders': {
      id: '/retailer/orders'
      path: '/orders'
      fullPath: '/retailer/orders'
      preLoaderRoute: typeof RetailerOrdersRouteImport
      parentRoute: typeof RetailerRouteRoute
    }
    '/retailer/order': {
      id: '/retailer/order'
      path: '/order'
      fullPath: '/retailer/order'
      preLoaderRoute: typeof RetailerOrderRouteImport
      parentRoute: typeof RetailerRouteRoute
    }
    '/retailer/ledger': {
      id: '/retailer/ledger'
      path: '/ledger'
      fullPath: '/retailer/ledger'
      preLoaderRoute: typeof RetailerLedgerRouteImport
      parentRoute: typeof RetailerRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/share-log': {
      id: '/_authenticated/share-log'
      path: '/share-log'
      fullPath: '/share-log'
      preLoaderRoute: typeof AuthenticatedShareLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/route-optimization': {
      id: '/_authenticated/route-optimization'
      path: '/route-optimization'
      fullPath: '/route-optimization'
      preLoaderRoute: typeof AuthenticatedRouteOptimizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconcile': {
      id: '/_authenticated/reconcile'
      path: '/reconcile'
      fullPath: '/reconcile'
      preLoaderRoute: typeof AuthenticatedReconcileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-reminders': {
      id: '/_authenticated/payment-reminders'
      path: '/payment-reminders'
      fullPath: '/payment-reminders'
      preLoaderRoute: typeof AuthenticatedPaymentRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demand-consolidation': {
      id: '/_authenticated/demand-consolidation'
      path: '/demand-consolidation'
      fullPath: '/demand-consolidation'
      preLoaderRoute: typeof AuthenticatedDemandConsolidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-status': {
      id: '/_authenticated/delivery-status'
      path: '/delivery-status'
      fullPath: '/delivery-status'
      preLoaderRoute: typeof AuthenticatedDeliveryStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-demand': {
      id: '/_authenticated/delivery-demand'
      path: '/delivery-demand'
      fullPath: '/delivery-demand'
      preLoaderRoute: typeof AuthenticatedDeliveryDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crates': {
      id: '/_authenticated/crates'
      path: '/crates'
      fullPath: '/crates'
      preLoaderRoute: typeof AuthenticatedCratesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-reconciliation': {
      id: '/_authenticated/cash-reconciliation'
      path: '/cash-reconciliation'
      fullPath: '/cash-reconciliation'
      preLoaderRoute: typeof AuthenticatedCashReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/$id': {
      id: '/_authenticated/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AuthenticatedSuppliersIdRouteImport
      parentRoute: typeof AuthenticatedSuppliersRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/challan': {
      id: '/_authenticated/purchases/challan'
      path: '/purchases/challan'
      fullPath: '/purchases/challan'
      preLoaderRoute: typeof AuthenticatedPurchasesChallanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/new': {
      id: '/_authenticated/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-ledger/$id': {
      id: '/_authenticated/customer-ledger/$id'
      path: '/customer-ledger/$id'
      fullPath: '/customer-ledger/$id'
      preLoaderRoute: typeof AuthenticatedCustomerLedgerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSuppliersRouteChildren {
  AuthenticatedSuppliersIdRoute: typeof AuthenticatedSuppliersIdRoute
}

const AuthenticatedSuppliersRouteChildren: AuthenticatedSuppliersRouteChildren =
  {
    AuthenticatedSuppliersIdRoute: AuthenticatedSuppliersIdRoute,
  }

const AuthenticatedSuppliersRouteWithChildren =
  AuthenticatedSuppliersRoute._addFileChildren(
    AuthenticatedSuppliersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCashReconciliationRoute: typeof AuthenticatedCashReconciliationRoute
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedCratesRoute: typeof AuthenticatedCratesRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedDeliveryDemandRoute: typeof AuthenticatedDeliveryDemandRoute
  AuthenticatedDeliveryStatusRoute: typeof AuthenticatedDeliveryStatusRoute
  AuthenticatedDemandConsolidationRoute: typeof AuthenticatedDemandConsolidationRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentRemindersRoute: typeof AuthenticatedPaymentRemindersRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReconcileRoute: typeof AuthenticatedReconcileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRouteOptimizationRoute: typeof AuthenticatedRouteOptimizationRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShareLogRoute: typeof AuthenticatedShareLogRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRouteWithChildren
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCustomerLedgerIdRoute: typeof AuthenticatedCustomerLedgerIdRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedOrdersNewRoute: typeof AuthenticatedOrdersNewRoute
  AuthenticatedPurchasesChallanRoute: typeof AuthenticatedPurchasesChallanRoute
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCashReconciliationRoute: AuthenticatedCashReconciliationRoute,
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedCratesRoute: AuthenticatedCratesRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedDeliveryDemandRoute: AuthenticatedDeliveryDemandRoute,
  AuthenticatedDeliveryStatusRoute: AuthenticatedDeliveryStatusRoute,
  AuthenticatedDemandConsolidationRoute: AuthenticatedDemandConsolidationRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentRemindersRoute: AuthenticatedPaymentRemindersRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReconcileRoute: AuthenticatedReconcileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRouteOptimizationRoute: AuthenticatedRouteOptimizationRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShareLogRoute: AuthenticatedShareLogRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRouteWithChildren,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCustomerLedgerIdRoute: AuthenticatedCustomerLedgerIdRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedOrdersNewRoute: AuthenticatedOrdersNewRoute,
  AuthenticatedPurchasesChallanRoute: AuthenticatedPurchasesChallanRoute,
  AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RetailerRouteRouteChildren {
  RetailerLedgerRoute: typeof RetailerLedgerRoute
  RetailerOrderRoute: typeof RetailerOrderRoute
  RetailerOrdersRoute: typeof RetailerOrdersRoute
  RetailerProfileRoute: typeof RetailerProfileRoute
  RetailerIndexRoute: typeof RetailerIndexRoute
}

const RetailerRouteRouteChildren: RetailerRouteRouteChildren = {
  RetailerLedgerRoute: RetailerLedgerRoute,
  RetailerOrderRoute: RetailerOrderRoute,
  RetailerOrdersRoute: RetailerOrdersRoute,
  RetailerProfileRoute: RetailerProfileRoute,
  RetailerIndexRoute: RetailerIndexRoute,
}

const RetailerRouteRouteWithChildren = RetailerRouteRoute._addFileChildren(
  RetailerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RetailerRouteRoute: RetailerRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
